### ISSUE TITLE
Koa parameter names don't match zod/openapi schema and causes validation errors

### ISSUE THREAD

**Issue by ADRFranklin** [mnahkies/openapi-code-generator#118]
So for example this is what I have in my openapi schema
```yaml
  /v1/users/{user_id}:
    get:
      operationId: UserGetById
      description: Get a user by ID.
      tags: [users]
      parameters:
        - name: user_id
          required: true
          in: path
          schema: { $ref: '#/components/schemas/Identifier' }
      responses:
        default: { $ref: '#/components/responses/InternalServerError' }
        '404': { $ref: '#/components/responses/NotFound' }
        '401': { $ref: '#/components/responses/Unauthorised' }
        '200': { $ref: '#/components/responses/UserGetByIdOK' }
```

as you can see I have the parameter as `user_id` and the generated schema for this becomes 
```ts
const userGetByIdParamSchema = z.object({ user_id: s_Identifier })
```

so far this all looks fine, until you look at the route that is generated
```ts
router.get("userGetById", "/v1/users/:userId", async (ctx, next) => { ... }
```

and now you'll notice it's checking against `userId` and not `user_id` which leads to a validation error. I'm aware I could just rename the parameter in my openapi file to match the koa parameter, but it's probably a good idea to address this, so it's not an annoying requirement.

**Comment by mnahkies** [comment]
Good spot, thanks for reporting. Fixed in #120, apologies for the delay was taking a bit of a break over Christmas.
