### ISSUE TITLE
Document compability / completeness for OpenAPI 3.0.3

### ISSUE THREAD

**Issue by mnahkies** [mnahkies/openapi-code-generator#60]
Assess and document the projects completeness for support of OpenAPI 3.0.3

Submit / link to issues where there are gaps.

**Comment by ADRFranklin** [comment]
Will you be stopping at 3.0.3 or will there be eventual support for 3.1.x?

Right now my openapi schema is designed for 3.1.x, which results in errors and has made to restructure things for now until support for 3.1.x exists.

**Comment by mnahkies** [comment]
I've cut a [v0.2.0](https://github.com/mnahkies/openapi-code-generator/releases/tag/v0.2.0) with some basic support for `3.1.x` - primarily just supporting `type` being an array / removal of `nullable` at this stage.

It's definitely the intention to support it, though I've been mostly focused on `3.0.3` since that seems to have the most usage still from what I've seen.

If you try it out I'd be interested in any hurdles you hit - it's hard to know what to prioritize supporting.
